### ISSUE TITLE
Resource leak when mutexes are used with multicore

### ISSUE THREAD

**Issue by kaneplusplus** [kaneplusplus/synchronicity#2]
See [here](https://github.com/kaneplusplus/bigmemory/issues/31).

**Comment by nmanuben** [comment]
Hi,

I'm using the package bigmemory only, without synchronicity, and I'm getting shared memory leaks in some situations where the R process using bigmemory objects is killed or when the function that creates and uses the objects is stopped with Ctrl^C. 

Do I need to install synchronicity to avoid this bug? Is the bug solved in any development version?

Best regards,
Nicolau
