### ISSUE TITLE
No build for Windows

### ISSUE THREAD

**Issue by adamryczkowski** [kaneplusplus/synchronicity#8]
Dear kaneplusplus.
Why there are no binary builds for Windows? In what time frame (if any) are you going to maintain this package?

**Comment by kaneplusplus** [comment]
If you have `devtools` (with Rtools) you should be able to install with:

``` r
library(devtools)
install_github("kaneplusplus/synchronicity")
```

**Comment by agrueneberg** [comment]
I still don't see a Windows build on CRAN. According to https://cran.r-project.org/bin/windows/contrib/3.5/ReadMe:

```
Some package are Unix only, including
	RBerkeley, doMC, gpda, nice, synchronicity, uaparserjs
```

Is this still the case? I don't see an `OS_type` field in the `DESCRIPTION` file, so I am wondering why synchronicity is excluded?

**Comment by kaneplusplus** [comment]
Thanks very much for pointing this out. The version on CRAN is outdated. I'll upload today.

**Comment by agrueneberg** [comment]
Thanks! What do you mean by outdated? The version on CRAN matches the current version in master (1.3.4).

**Comment by kaneplusplus** [comment]
Hmm... you are right. I assumed that a Windows version was not available on CRAN becuase it used the last version that did include the `OS_type` directive.

I've bump the version and sent to the win builder. If there are no problem then I'l resubmit to CRAN. If that doesn't work, then I'll email a CRAN maintainer. I'll follow up with updates.

**Comment by agrueneberg** [comment]
It appears that the `OS_type` line hasn't been included since ~2015 (0a6e462dfd4935c45afb492105422e422cb045da). I'm wondering if the package is somehow blacklisted on CRAN, because it passes `R CMD check` on AppVeyor without issues.

**Comment by kaneplusplus** [comment]
Thanks for tracking this down. The submission was sent last night and I put a note in indicating that we do support Windows but it's not showing up.

**Comment by agrueneberg** [comment]
Any news? I noticed that the new version is not up yet.

**Comment by kaneplusplus** [comment]
OK, I'm sending an email. Thanks very much for the reminder.

**Comment by kaneplusplus** [comment]
Got an email from Uwe, the Windows build should be up in the next few days.

**Comment by agrueneberg** [comment]
Great, thanks! What was the reason?

**Comment by kaneplusplus** [comment]
I'm not sure; he didn't say. My hunch is that the `OS_type` option was preserved on CRAN.

**Comment by agrueneberg** [comment]
Interesting; probably because it's an older package. One of my packages used to have `OS_type` and I eventually managed to drop it, and didn't have this problem. In any case, the build is online and the issue can be closed. Thanks for looking into this!

**Comment by kaneplusplus** [comment]
It's up.

**Comment by kaneplusplus** [comment]
Thanks again for pointing this out and seeing it through with me!
